apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wm2g
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wm2g
    app.kubernetes.io/part-of: ci10t-786-0030-app
  name: devfile-sample-wm2g
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-wm2g
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-wm2g
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0030-tenant/ci10t-786-0030-app/devfile-sample-wm2g@sha256:fe7765a61e8433926e70e6c0ebede901e9b6973c5e0acf899bd54ff84bf55cb2
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
