apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wm2g
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0030-tenant/ci10t-786-0030-app/devfile-sample-wm2g@sha256:fe7765a61e8433926e70e6c0ebede901e9b6973c5e0acf899bd54ff84bf55cb2
        name: my-nodejs
        resources: {}
status: {}
